config/routes.rb
RITSurv::Application.routes.draw do
  resources :amazoncards

  resources :amazon_gift_cards

  mount Surveyor::Engine => "/surveys", :as => "surveyor"

  root :to => 'consent#nothing_here'

  match ':controller(/:action(/:id))(.:format)'
  match 'thanks', :to => 'thanks#index', :as => 'thanks_index'
end

app/models/amazon_gift_card.rb
class AmazonGiftCard < ActiveRecord::Base
  attr_accessible :code, :used
end

app/controllers/amazon_gift_cards_controller.rb
class AmazonGiftCardsController < ApplicationController
  # GET /amazon_gift_cards
  # GET /amazon_gift_cards.json
  def index
    @amazon_gift_cards = AmazonGiftCard.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @amazon_gift_cards }
    end
  end

  # GET /amazon_gift_cards/1
  # GET /amazon_gift_cards/1.json
  def show
    @amazon_gift_card = AmazonGiftCard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @amazon_gift_card }
    end
  end

  # GET /amazon_gift_cards/new
  # GET /amazon_gift_cards/new.json
  def new
    @amazon_gift_card = AmazonGiftCard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @amazon_gift_card }
    end
  end

  # GET /amazon_gift_cards/1/edit
  def edit
    @amazon_gift_card = AmazonGiftCard.find(params[:id])
  end

  # POST /amazon_gift_cards
  # POST /amazon_gift_cards.json
  def create
    @amazon_gift_card = AmazonGiftCard.new(params[:amazon_gift_card])

    respond_to do |format|
      if @amazon_gift_card.save
        format.html { redirect_to @amazon_gift_card, notice: 'Amazon gift card was successfully created.' }
        format.json { render json: @amazon_gift_card, status: :created, location: @amazon_gift_card }
      else
        format.html { render action: "new" }
        format.json { render json: @amazon_gift_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /amazon_gift_cards/1
  # PUT /amazon_gift_cards/1.json
  def update
    @amazon_gift_card = AmazonGiftCard.find(params[:id])

    respond_to do |format|
      if @amazon_gift_card.update_attributes(params[:amazon_gift_card])
        format.html { redirect_to @amazon_gift_card, notice: 'Amazon gift card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @amazon_gift_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /amazon_gift_cards/1
  # DELETE /amazon_gift_cards/1.json
  def destroy
    @amazon_gift_card = AmazonGiftCard.find(params[:id])
    @amazon_gift_card.destroy

    respond_to do |format|
      format.html { redirect_to amazon_gift_cards_url }
      format.json { head :no_content }
    end
  end
  
  
end

app/helpers/amazon_gift_cards_helper.rb
module AmazonGiftCardsHelper
end

app/views/amazon_gift_cards/_form.html.erb
<%= form_for(@amazon_gift_card) do |f| %>
  <% if @amazon_gift_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@amazon_gift_card.errors.count, "error") %> prohibited this amazon_gift_card from being saved:</h2>

      <ul>
      <% @amazon_gift_card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :used %><br />
    <%= f.number_field :used %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/amazon_gift_cards/edit.html.erb
<h1>Editing amazon_gift_card</h1>

<%= render 'form' %>

<%= link_to 'Show', @amazon_gift_card %> |
<%= link_to 'Back', amazon_gift_cards_path %>

app/views/amazon_gift_cards/index.html.erb
<h1>Listing amazon_gift_cards</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Used</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @amazon_gift_cards.each do |amazon_gift_card| %>
  <tr>
    <td><%= amazon_gift_card.code %></td>
    <td><%= amazon_gift_card.used %></td>
    <td><%= link_to 'Show', amazon_gift_card %></td>
    <td><%= link_to 'Edit', edit_amazon_gift_card_path(amazon_gift_card) %></td>
    <td><%= link_to 'Destroy', amazon_gift_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Amazon gift card', new_amazon_gift_card_path %>

app/views/amazon_gift_cards/new.html.erb
<h1>New amazon_gift_card</h1>

<%= render 'form' %>

<%= link_to 'Back', amazon_gift_cards_path %>

app/views/amazon_gift_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @amazon_gift_card.code %>
</p>

<p>
  <b>Used:</b>
  <%= @amazon_gift_card.used %>
</p>


<%= link_to 'Edit', edit_amazon_gift_card_path(@amazon_gift_card) %> |
<%= link_to 'Back', amazon_gift_cards_path %>